"""Built-in low-noise service profile definitions."""

from __future__ import annotations


WEB_PORTS = {
    80,
    81,
    82,
    83,
    88,
    443,
    591,
    593,
    8000,
    8008,
    8080,
    8081,
    8088,
    8090,
    8443,
    8800,
    8888,
    9000,
    9443,
}

UDP_DEFAULT_PORTS = {
    53,
    67,
    68,
    69,
    88,
    111,
    123,
    137,
    138,
    161,
    162,
    389,
    500,
    514,
    520,
    631,
    1434,
    1900,
    2049,
    4500,
    5353,
    11211,
}

SERVICE_PROFILES: dict[str, dict[str, object]] = {
    "web": {
        "ports": WEB_PORTS,
        "services": {
            "http",
            "http-alt",
            "http-proxy",
            "https",
            "ssl/http",
        },
        "banner_terms": {
            "apache",
            "apache-coyote",
            "caddy",
            "cherokee",
            "cloudflare",
            "gunicorn",
            "http",
            "httpapi",
            "httpd",
            "iis",
            "jetty",
            "lighttpd",
            "nginx",
            "openresty",
            "server:",
            "traefik",
            "tomcat",
            "werkzeug",
        },
        "scripts": ["http-title", "http-server-header"],
    },
    "tls": {
        "ports": {443, 465, 563, 636, 853, 989, 990, 993, 995, 8443, 9443, 5986},
        "services": {"https", "imaps", "ldaps", "pop3s", "ssl", "ssl/http", "smtps"},
        "banner_terms": {
            "certificate",
            "issuer",
            "ssl-cert",
            "starttls",
            "subject",
            "tls",
        },
        "scripts": ["ssl-cert"],
    },
    "smb": {
        "ports": {139, 445},
        "udp_ports": {137, 138},
        "services": {"microsoft-ds", "netbios-ssn", "smb"},
        "banner_terms": {
            "lanman",
            "microsoft-ds",
            "netbios",
            "samba",
            "smb",
            "smbd",
        },
        "scripts": ["smb-protocols", "smb2-security-mode", "smb2-time"],
        "impacket": ["samrdump", "rpcdump"],
    },
    "ssh": {
        "ports": {22, 2222},
        "services": {"ssh"},
        "banner_terms": {"dropbear", "libssh", "openssh", "ssh", "ssh-2.0"},
        "scripts": ["ssh-hostkey", "ssh2-enum-algos"],
    },
    "ftp": {
        "ports": {20, 21, 989, 990, 2121},
        "services": {"ftp", "ftp-data", "ftps", "ssl/ftp"},
        "banner_terms": {
            "filezilla",
            "ftp",
            "ftpd",
            "microsoft ftp",
            "proftpd",
            "pure-ftpd",
            "vsftpd",
        },
        "scripts": ["ftp-syst"],
    },
    "telnet": {
        "ports": {23, 2323},
        "services": {"telnet"},
        "banner_terms": {"telnet"},
        "scripts": ["telnet-encryption"],
    },
    "dns": {
        "ports": {53, 5353},
        "udp_ports": {53, 5353},
        "services": {"domain", "dns", "mdns"},
        "banner_terms": {"bind", "dns", "dnsmasq", "domain", "mdns", "named"},
        "scripts": ["dns-nsid"],
    },
    "dhcp": {
        "ports": set(),
        "udp_ports": {67, 68},
        "services": {"dhcp", "dhcps", "dhcpc", "bootps", "bootpc"},
        "banner_terms": {"bootp", "dhcp"},
        "scripts": [],
    },
    "tftp": {
        "ports": set(),
        "udp_ports": {69},
        "services": {"tftp"},
        "banner_terms": {"tftp"},
        "scripts": [],
    },
    "ntp": {
        "ports": set(),
        "udp_ports": {123},
        "services": {"ntp"},
        "banner_terms": {"ntp"},
        "scripts": ["ntp-info"],
    },
    "smtp": {
        "ports": {25, 465, 587, 2525},
        "services": {"smtp", "smtps", "submission"},
        "banner_terms": {
            "esmtp",
            "exim",
            "mailenable",
            "postfix",
            "sendmail",
            "smtp",
        },
        "scripts": ["smtp-commands"],
    },
    "pop3": {
        "ports": {110, 995},
        "services": {"pop3", "pop3s"},
        "banner_terms": {"pop3", "pop3d", "qpopper"},
        "scripts": ["pop3-capabilities"],
    },
    "imap": {
        "ports": {143, 993},
        "services": {"imap", "imaps"},
        "banner_terms": {"courier-imap", "imap", "imapd", "uw-imap"},
        "scripts": ["imap-capabilities"],
    },
    "rdp": {
        "ports": {3389},
        "services": {"ms-wbt-server", "rdp"},
        "banner_terms": {"ms-wbt-server", "rdp", "remote desktop", "terminal service"},
        "scripts": ["rdp-enum-encryption"],
    },
    "ldap": {
        "ports": {389, 636, 3268, 3269},
        "udp_ports": {389},
        "services": {"ldap", "ldaps"},
        "banner_terms": {"active directory", "ldap", "ldaps", "openldap"},
        "scripts": ["ldap-rootdse"],
    },
    "kerberos": {
        "ports": {88, 464, 749},
        "udp_ports": {88, 464},
        "services": {"kerberos", "kpasswd5", "krb5", "krb524"},
        "banner_terms": {"heimdal", "kerberos", "krb5", "mit kerberos"},
        "scripts": [],
    },
    "winrm": {
        "ports": {5985, 5986},
        "services": {"wsman"},
        "banner_terms": {"microsoft-httpapi", "winrm", "ws-management", "wsman"},
        "scripts": ["http-title", "http-server-header"],
    },
    "nfs": {
        "ports": {2049},
        "udp_ports": {2049},
        "services": {"nfs", "nfs_acl"},
        "banner_terms": {"mountd", "nfs", "nfs_acl"},
        "scripts": ["nfs-showmount"],
    },
    "rpc": {
        "ports": {111, 135},
        "udp_ports": {111},
        "services": {"rpcbind", "msrpc"},
        "banner_terms": {"msrpc", "portmapper", "rpcbind"},
        "scripts": ["rpcinfo"],
        "impacket": ["rpcdump"],
    },
    "snmp": {
        "ports": {161, 162},
        "udp_ports": {161, 162},
        "services": {"snmp", "snmptrap"},
        "banner_terms": {"net-snmp", "snmp"},
        "scripts": ["snmp-info"],
    },
    "mssql": {
        "ports": {1433, 1434},
        "udp_ports": {1434},
        "services": {"ms-sql", "ms-sql-m", "ms-sql-s"},
        "banner_terms": {"microsoft sql", "ms-sql", "mssql", "sql server"},
        "scripts": ["ms-sql-info"],
    },
    "mysql": {
        "ports": {3306, 33060},
        "services": {"mysql", "mysqlx"},
        "banner_terms": {"mariadb", "mysql", "percona"},
        "scripts": ["mysql-info"],
    },
    "postgres": {
        "ports": {5432, 5433},
        "services": {"postgres", "postgresql"},
        "banner_terms": {"postgres", "postgresql"},
        "scripts": [],
    },
    "redis": {
        "ports": {6379},
        "services": {"redis"},
        "banner_terms": {"redis"},
        "scripts": ["redis-info"],
    },
    "mongodb": {
        "ports": {27017, 27018, 27019},
        "services": {"mongodb"},
        "banner_terms": {"mongodb"},
        "scripts": ["mongodb-info"],
    },
    "elasticsearch": {
        "ports": {9200, 9300},
        "services": {"elasticsearch", "wap-wsp"},
        "banner_terms": {"elastic", "elasticsearch", "lucene"},
        "scripts": ["http-title", "http-server-header"],
    },
    "memcached": {
        "ports": {11211},
        "udp_ports": {11211},
        "services": {"memcache", "memcached"},
        "banner_terms": {"memcache", "memcached"},
        "scripts": ["memcached-info"],
    },
    "vnc": {
        "ports": {5800, 5900, 5901, 5902},
        "services": {"vnc", "vnc-http"},
        "banner_terms": {"realvnc", "rfb", "tightvnc", "ultravnc", "vnc"},
        "scripts": ["vnc-info"],
    },
    "rsync": {
        "ports": {873},
        "services": {"rsync"},
        "banner_terms": {"rsync"},
        "scripts": [],
    },
    "docker": {
        "ports": {2375, 2376},
        "services": {"docker"},
        "banner_terms": {"docker", "docker engine"},
        "scripts": ["http-title", "http-server-header"],
    },
    "kubernetes": {
        "ports": {6443, 8001, 8080, 10250, 10255},
        "services": {"kube-apiserver", "kubelet", "kubernetes"},
        "banner_terms": {"kube-apiserver", "kubelet", "kubernetes"},
        "scripts": ["http-title", "http-server-header"],
    },
    "ike": {
        "ports": set(),
        "udp_ports": {500, 4500},
        "services": {"ike", "isakmp", "ipsec-nat-t"},
        "banner_terms": {"ike", "ipsec", "isakmp", "nat-t"},
        "scripts": ["ike-version"],
    },
    "syslog": {
        "ports": set(),
        "udp_ports": {514},
        "services": {"syslog"},
        "banner_terms": {"syslog"},
        "scripts": [],
    },
    "ssdp": {
        "ports": set(),
        "udp_ports": {1900},
        "services": {"ssdp", "upnp"},
        "banner_terms": {"ssdp", "upnp"},
        "scripts": [],
    },
}
